ARG APP_IMAGE_NAME
ARG APP_IMAGE_TAG

FROM ${APP_IMAGE_NAME}:${APP_IMAGE_TAG} AS app

FROM nginx:1.29.3-alpine

WORKDIR /var/www/html

COPY --from=app /var/www/html/public /var/www/html/public
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
